name: Product MF CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          npm ci || (rm -rf node_modules package-lock.json && npm install)

      - name: Build
        run: npm run build

      - name: Install Linux Rolldown binding
        run: npm install --no-save @rolldown/binding-linux-x64-gnu -w product-mf

      - name: Build
        run: npm run build -w product-mf  

      - name: Install Dependencies
        un: npm ci -w product-mf